version: '3.8'
services:
  web:
    build:
      context: ./web
    depends_on:
      - dbweb
      - auth
    env_file:
      - ./web/.env
    ports:
      - "8081:8081"
    volumes:
      - ./web:/usr/src/app
    command: ["air", "-c", ".air.toml"]

  dbweb:
    image: postgres:alpine
    env_file:
      - ./web/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres-db-web:/var/lib/postgresql/data
  
  dbauth:
    image: postgres:alpine
    env_file:
      - ./authService/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-auth:/var/lib/postgresql/data


  auth:
    build:
      context: ./authService
    depends_on:
      - dbauth
    env_file:
      - ./authService/.env
    ports:
      - "8082:8082"
    volumes:
      - ./authService:/usr/src/app
    command: ["air", "-c", ".air.toml"]

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres-db-web:
  postgres-db-auth:
